@baseUrl = http://localhost:3000
###
GET {{baseUrl}}/api/hello

###
GET {{baseUrl}}/api/word/daily

###
# @name createRoom

POST {{baseUrl}}/api/room
Content-Type: application/json

{
  "word": "семпл",
  "type": "private",
  "duration": 2
}
###
@roomId = {{createRoom.response.body.$.id}}
###

# @name guessWordIncorrect
POST {{baseUrl}}/api/word/guess
Content-Type: application/json

{
  "roomId": "{{roomId}}",
  "word": "лесок"
}

###

# @name guessWordCorrect
POST {{baseUrl}}/api/word/guess
Content-Type: application/json

{
  "roomId": "{{roomId}}",
  "word": "семпл"
}

###